version: '3'

volumes:
  hm.cache:

networks:
  hm.net:

services:

  hm.cache:
    restart: always
    container_name: home-monitor-cache
    image: redis:7.0-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - hm.cache:/data
    networks:
      - hm.net

  hm.api:
    restart: always
    container_name: home-monitor-api
    build:
      context: .
    ports:
      - 3001:3001
    depends_on:
      - hm.cache
    links:
      - hm.cache
    env_file:
      - .env
    environment:
      REDIS_HOST: hm.cache
      REDIS_PORT: 6379
    networks:
      - hm.net
